### ISSUE TITLE
Changing props after first render does not update the component

### ISSUE THREAD

**Issue by DustinJSilk** [qwikifiers/qwik-image#2]
It's seems reactivity is not working. The image component renders correctly on the first render, however, if you need to change any of the input props like it's layout or src after creating the component, it doesn't update.

This looks like it is because the logic for generating the src, sizes, and layouts is coded at the component level rather than in a reactive task$ or computed$ function.

**Comment by gioboa** [comment]
Thanks for the report. Can you post a snippet for your you case pls?

**Comment by DustinJSilk** [comment]
Thanks for you amazing work here! Yes i am building a real application, i have a new version going live to deprecate a large part of the old angular app which goes live this week, i'll share a link once its up

**Comment by gioboa** [comment]
I released the new version [qwik-image-0.0.7](https://github.com/qwikifiers/qwik-image/releases/tag/qwik-image-0.0.7) with this feature

**Comment by DustinJSilk** [comment]
Thanks @gioboa ! This is now live on my new search page https://staze.com/
