### ISSUE TITLE
Wrong transformed height when aspectRatio is provided

### ISSUE THREAD

**Issue by ilianiv** [qwikifiers/qwik-image#4]
Hello!
I think this calculation here is wrong:

https://github.com/qwikifiers/qwik-image/blob/main/packages/qwik-image/src/lib/image.tsx#L163
```
for await (const breakpoint of breakpoints.sort()) {
    let transformedHeight =
      typeof height === 'string' ? parseInt(height, 10) : height;
    if (height && aspectRatio) {
      transformedHeight = Math.round(breakpoint * aspectRatio);
                                               ^^^
    }
```
The aspect ratio of an image is the ratio of its width to its height.
```
Aspect Ratio = Width / Height 
Height = Width / Aspect Ratio
```
so if we want to transform the height we should divide the width by the aspect ratio
```
transformedHeight = Math.round(breakpoint / aspectRatio);
```

**Comment by gioboa** [comment]
Hey @ilianiv thanks for your report. I will fix it.

**Comment by gioboa** [comment]
I released the new version with this fix. Thanks @ilianiv 👍

**Comment by ilianiv** [comment]
Thanks @gioboa
